### ISSUE TITLE
7 rows in the CSV file but expected was 3

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode-spring-junit#1]
_@aghorpade wrote-_
===
@nirmalchandra  - yes,it has entered three entries into csv report. PFB.
![image](https://user-images.githubusercontent.com/5318345/44002580-85339990-9e62-11e8-82b2-20658a415bbf.png)

_@umangsingh123 wrote-_
===

I got your example and my test class working . Would tell you the problem.
So in test cases i was initializing cassandra. So the issue was every time it was trying to start and stop the server .
So i moved that code into Config java file so that for the context we use same object and did a `gradle clean build` and i see the requests and response in the csv file .
The only question now i have for the closure is that i see 7 rows in the CSV file with the following configs 
number.of.threads=3
ramp.up.period.in.seconds=2
loop.count=1

![result](https://user-images.githubusercontent.com/22513696/44044725-1ff2d1b0-9eec-11e8-8e51-8db21add6545.jpeg)

Is that expected. 
Also i liked your page , let me know if you can see that.
Could we get some more beneficial reports along with the basic CSV ones .
Thanks a lot for the quick help and support.

**Comment by umangsingh123** [comment]
So we would be track the count issue with this thread .

**Comment by authorjapps** [comment]
@umangsingh123, I am still trying to understand this issue. Isn't it possible to strip out your business code and keep only the skeletons to reproduce this in this repo? I mean you can add a single test to the `MachineLearningServiceTest.java` running which we should be able to reproduce this.

Some more observations from the screen shot of your report-
<img height="200" width="208" alt="screen shot 2018-08-16 at 8 29 21 am" src="https://user-images.githubusercontent.com/12598420/44184835-911d8a80-a12e-11e8-9a44-6ecc17812bbf.png">

- The 7 rows have the time stamps in the `59th min`, but the seconds are as follows(if sorted)
  - 6th
  - 6th
  - 7th
  - 14th
  - 20th
  - 21st
  - 21st

But the `ramp.up.period.in.seconds=2` which means within 2 seconds 3 requests should have been fired. That means `6th, 6th, 7th ` looks good to me.

Next `loop.count=1` means the tests should terminate(will not repeat) after firing 3 times.

Hence 14th, 21st, 21st looks little bit weird to me.

One thing I am suspecting is if the target was not cleared prior to running the same test, then the report gets amended to the existing records. But you wrote you did a `graddle clean`. I am assuming it's equivalent to `mvn clean`. 

- Another observation, when you do `graddle clean build`, is it equivalent to something `mvn clean install` which runs all tests in the repo and there is a possibility the tests are fired from another `load test` somewhere in the repo.

- Another suggession will be just delete the target folder and run the load test from IDE (not via gradle) and see the report.

It will be help us to identify the issue or to fix it quicker if somehow we can reproduce it.

**Comment by umangsingh123** [comment]
Yes Gradle clean build is same as maven clean install.
If I am running just the test case for some reasons the first run passes but then all fail i.e if I say thread count of 3 then first passes and rest fails . So I thought this might be some limitation and as per you I did a clean build and that worked but result was the one I attached .
There were no 2 test cases I have stripped the first column but I clearly see that the same test class and method was executed and I had also deleted the previous ones and also did a clean build so no chances of old one to be there .
I was thinking just one thing that the loadrunner class has zero code load runner as the run with and the actual unit test also has the extension of springjunitrunner (zerocodespringrunner) .is it because of that it's duplicating .
But the load configs are only on the runner class not the actual junit.
Let me know if you need the files and I can upload the skeletons with the project.

**Comment by authorjapps** [comment]
> Let me know if you need the files and I can upload the skeletons with the project.

Yes, that will be very useful to us to debug. You can create a repo of **yours** which we can simply clone and run,
or you can fork **this repo** and push your code into that and let us know. 

Now I have added you as collaborator, click this link and accept, here is the [link](https://github.com/authorjapps/zerocode-spring-junit/invitations) 

In the mean time, please see(and paste the screen shot similar to below) what it outputs to the console in terms of the following.
<img width="476" alt="screen shot 2018-08-16 at 8 32 25 am" src="https://user-images.githubusercontent.com/12598420/44185003-74358700-a12f-11e8-84bb-98980f12fe04.png">

**Comment by authorjapps** [comment]
@aghorpade, can you please accept this invitee [click n accept](https://github.com/authorjapps/zerocode-spring-junit/invitations) ?

**Comment by umangsingh123** [comment]
Hi ,
I did some clean up and tested again same results it's 7 times .
Again i ran as Junit it fails says one test passed and other 2 fails (with thread count of 3 ).
Run as Gradle clean build all pass 7 records in CSV.

I have added the code in the below folder 
https://github.com/authorjapps/zerocode-spring-junit/tree/master/src/main/java/org/zerocode/spring/umang/demo

Demo folder has all the classes . Didn't want to break any of your existing running code so added all in one.
The test classes are the Unit test classes .

the Gradle dependencies which you can do in maven would be as below 
`
    compile 'org.springframework.data:spring-data-cassandra'
    // JUnit and Mockito dependencies
    testCompile 'junit:junit'
    testCompile 'org.mockito:mockito-core'
    testCompile 'org.springframework:spring-test'
    compile 'org.cassandraunit:cassandra-unit-spring'
    testCompile 'org.assertj:assertj-core'
	compile 'com.datastax.cassandra:cassandra-driver-core'
	compile 'com.datastax.cassandra:cassandra-driver-mapping'
	compile 'org.springframework.hateoas:spring-hateoas'
    compile group: 'org.jsmart', name: 'zerocode-rest-bdd', version: '1.2.6'
    compile group: 'org.jsmart', name: 'micro-simulator', version: '1.1.10'`


Hope this helps . So we are doing cassandra insert operation alongwith a rest call using resttemplate . So havent attached the DAO.
I have built some custom stubbers so you can remove those classes.
The load props are the same as i gave earlier.
This would definitely not compile.
This is the most simplest one.

Let me know if you need any further information.

**Comment by authorjapps** [comment]
That's not much useful as it has got compilation errors. It doesn't help us to reproduce the issue anyway. If possible you create a new brach in this repo and push the `graddle project`(only the relevant tests, not the entire code), which we can compile, build and reproduce the issue.
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[6,38] package org.apache.commons.collections does not exist
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[7,32] package org.springframework.http does not exist
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[8,32] package org.springframework.http does not exist
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[13,10] package rx does not exist
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[14,20] package rx.observers does not exist
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[29,75] cannot find symbol

[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[29,16] cannot find symbol
  symbol:   class Observable
  location: class com.bestbuy.esp.service.DetailsService
[ERROR] /github/zerocode-spring-junit/src/main/java/org/zerocode/spring/umang/demo/DetailsService.java:[29,27] cannot find symbol
  symbol:   class ResponseEntity
 
 200 more errors...
```
Can you join [Gitter here](https://gitter.im/zerocode-testing/help-and-usage) and some of us will ping you and then probably followed by a screen sharing session will help us to identify the issue.

**Comment by umangsingh123** [comment]
Yes joining jitter would be a good option because there is lot of foundational work which I have done for this but the errors which you are showing is because of rxjava1.0 not there and Lang Apache not there .
You can add those dependencies and try.
But jitter is the best cam we keep a time and I can log in . I am in cst timezone

**Comment by authorjapps** [comment]
Did you get chance to read the below which I embedded in earlier comment ?

_Author note:_ 
===

> Again i ran as Junit it fails says one test passed and other 2 fails (with thread count of 3 ).

This sounds good. Does that mean you get `3 records` with `2 failed` status in the `CSV` ?

> Run as Gradle clean build all pass 7 records in CSV.

Here during the build `life cycle` gradle or maven runs all the tests. That means- The individual JUnit tests run which puts some entry into the `CSV` report, then the load tests run which puts `3 or number of thread` entries into the `CSV` report. That's why probably you see more than 3 records.

The same thing(more records) happens when we run using `mvn clean install` or `mvn clean test` too. If you **don't want** the JUnit to run individually **outside the load-test**, you can achieve that anyway. This way you get the report matching your `number of threads`

First please figure out if this is the issue and let us know !

**Comment by authorjapps** [comment]
> But jitter is the best cam we keep a time and I can log in . I am in cst timezone

We are in BST time zone which is CST + 6 hrs I guess. We will propose a time soon. 

In the mean time-
Can you please fix the compilation errors in a branch ?

> Yes joining jitter would be a good option because there is lot of foundational work which I have done for this but the errors which you are showing is because of rxjava1.0 not there and Lang Apache not there .
You can add those dependencies and try.

Your code is now in this branch [ISS-1](https://github.com/authorjapps/zerocode-spring-junit/tree/ISS-1).
Please fix them in this branch and let us know then we will run to reproduce the issue.

**Comment by umangsingh123** [comment]
Ok would work on fixing compilation issues but when can we do the jitter call

**Comment by umangsingh123** [comment]
When can we have the call?

**Comment by authorjapps** [comment]
Have you joined [Gitter here](https://gitter.im/zerocode-testing/help-and-usage) ? We couldn't find you. Just say `Hello` there to locate you.

**Comment by umangsingh123** [comment]
Hi ,
Please give me time at one day then we can connect other day . So tomorrow on the same thread you can give time and we can connect day after or same . But i would like to have time in advance

**Comment by umangsingh123** [comment]
Joined Gitter and pinged you.

**Comment by authorjapps** [comment]
@umangsingh123 , Great! we have pinged you there **two timings**, one on **Friday**, another on **Satday**. But prior to that, pls fix the compilation issues in the branch, otherwise the session might not be very helpful.

@aghorpade , @officiallysameer, @nirmalchandra FYI-
> Friday evening 9pm BST(UK time) or Satday 5pm BST looking good to us. 

Let me know in case of any change needed !

**Comment by umangsingh123** [comment]
Yes definetly i am trying to fix those but just got busy in some prod stuff . you cam give the time over here and i can join at that time.

**Comment by umangsingh123** [comment]
Hi ,
I have compiled the code in my local . I tried uploading but saw that you have deleted the folders from Repo so adding the zip of demo folder and the pom. xml here . Don't want to break you repo because these are just skeleton classes
[demo.zip](https://github.com/authorjapps/zerocode-spring-junit/files/2324907/demo.zip)
[pom.xml.zip](https://github.com/authorjapps/zerocode-spring-junit/files/2324909/pom.xml.zip)

Hope this helps

**Comment by authorjapps** [comment]
@umangsingh123 , again you missed it. I have mentioned here that your code is in a branch now. You can easily fix it there than uploading directly to master making the `master` unusable.
See this comment : https://github.com/authorjapps/zerocode-spring-junit/issues/1#issuecomment-414067975

Btw, in local, I copied the classes and picked the POM your attachment, there is no compilation error, but it's unable to run the test due to probably some version mismatch problem. See below-
>java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationAttributes.getAliasedStringArray(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)[Ljava/lang/String;
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:125)


Test - `org.zerocode.spring.umang.junit.MachineLearningServiceTest#testGetCarrierCharges`

Anyway, please fix all these in the branch whenever you get chance.

**Comment by umangsingh123** [comment]
Hi when can we do the call at least you can see the demo once and see if I had missed anything. I would work on that and checking the code to right branch. I believe we were meeting today and I was online on gitter . 
Let me know any other time

**Comment by authorjapps** [comment]
Hello mate, one of us pinged you at 11pm BST Yday, but somehow we missed you as you seemed offline then. We got your messages 30min later and we were offline then. We will coordinate again on `gitter` n work out a timing.

**Comment by authorjapps** [comment]
@umangsingh123 , finally we made it :-). Problem sorted.
The earlier relevant comment was here - https://github.com/authorjapps/zerocode-spring-junit/issues/1#issuecomment-414067760

Can I  close this ticket now?

**Comment by umangsingh123** [comment]
Thanks for the help . I would do some more tests today and as i am done with those would let you know on the closure

**Comment by authorjapps** [comment]
Let us close this ticket. Anyways, you can open a new one whenever you encounter a **new** issue. 👍
